# Generated by Django 4.2.7 on 2025-12-13 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(help_text='grams per 100g', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(help_text='grams per 100g', validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.FloatField(help_text='grams per 100g', validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(default=0, help_text='grams per 100g', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('quantity', models.FloatField(help_text='Quantity in grams', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_protein', models.FloatField(help_text='grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carbs', models.FloatField(help_text='grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_fat', models.FloatField(help_text='grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
