# Generated by Django 4.2.7 on 2025-12-15 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_weightentry_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('breakfast_time', models.TimeField(blank=True, default='08:00', null=True)),
                ('lunch_time', models.TimeField(blank=True, default='13:00', null=True)),
                ('dinner_time', models.TimeField(blank=True, default='19:00', null=True)),
                ('snack_time', models.TimeField(blank=True, default='15:00', null=True)),
                ('active_days', models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated days (0=Monday, 6=Sunday)', max_length=20)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Reminder Settings',
                'verbose_name_plural': 'Meal Reminder Settings',
            },
        ),
    ]
