# Generated by Django 4.2.7 on 2025-12-17 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mealremindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('usda', 'USDA FoodData Central'), ('openfoodfacts', 'Open Food Facts'), ('nutritionix', 'Nutritionix')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(blank=True, help_text='mg per 100g', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(blank=True, help_text='grams per 100g', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='usda_fdc_id',
            field=models.IntegerField(blank=True, help_text='USDA FoodData Central ID', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['usda_fdc_id'], name='api_food_usda_fd_d464ac_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['data_source'], name='api_food_data_so_f65773_idx'),
        ),
    ]
