# Generated by Django 4.2.7 on 2025-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_food_data_source_food_sodium_food_sugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealremindersettings',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Enable email notifications for meal reminders'),
        ),
        migrations.AddField(
            model_name='mealremindersettings',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email address is verified'),
        ),
    ]
