# Generated by Django 4.2.7 on 2025-12-17 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_waterintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_enabled', models.BooleanField(default=True, help_text='Show water widget on dashboard')),
                ('unit', models.CharField(choices=[('ml', 'Milliliters (ml)'), ('fl_oz', 'Fluid Ounces (fl oz)'), ('cups', 'Cups')], default='fl_oz', help_text='Preferred unit for water display', max_length=10)),
                ('daily_goal_ml', models.FloatField(default=2000, help_text='Daily water goal in milliliters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Settings',
                'verbose_name_plural': 'Water Settings',
            },
        ),
    ]
