# Generated by Django 4.2.7 on 2025-12-19 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_recipe_alter_meal_food_alter_meal_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_enabled', models.BooleanField(default=True, help_text='Show fasting widget on dashboard')),
                ('protocol', models.CharField(choices=[('16:8', '16:8 (16 hours fast, 8 hours eating)'), ('18:6', '18:6 (18 hours fast, 6 hours eating)'), ('20:4', '20:4 (20 hours fast, 4 hours eating)'), ('24:0', '24:0 (24 hours fast)'), ('custom', 'Custom')], default='16:8', help_text='Preferred fasting protocol', max_length=10)),
                ('custom_fasting_hours', models.IntegerField(blank=True, default=16, help_text='Custom fasting duration in hours', null=True)),
                ('eating_window_start', models.TimeField(default='12:00', help_text='Start time of eating window (HH:MM)')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable fasting notifications')),
                ('notify_fast_start', models.BooleanField(default=True, help_text='Notify when fasting period starts')),
                ('notify_fast_end', models.BooleanField(default=True, help_text='Notify when fasting period ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fasting Settings',
                'verbose_name_plural': 'Fasting Settings',
            },
        ),
        migrations.CreateModel(
            name='FastingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When the fasting period started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the fasting period ended (null if ongoing)', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes (calculated)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this fasting session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='api_fasting_user_id_634b50_idx'), models.Index(fields=['user', 'is_active'], name='api_fasting_user_id_fb7c73_idx')],
            },
        ),
    ]
