# Generated by Django 4.2.7 on 2025-12-14 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='List of allergies'),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('keto', 'Keto'), ('paleo', 'Paleo')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, help_text='Dietary restrictions'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_display_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=10),
        ),
        migrations.CreateModel(
            name='PsychFoodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening_overeating', models.BooleanField(default=False)),
                ('sweet_stress', models.BooleanField(default=False)),
                ('irregular_eating', models.BooleanField(default=False)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI analysis result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psych_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
