# Generated by Django 4.2.7 on 2025-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allergies_user_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target weight in kg', null=True),
        ),
    ]
